#!/usr/bin/env bash
# Loops from1 to 20  and displays:
#   4 and then bad luck from China for the 4th loop iteration
#   9 and then bad luck from Japan for the 9th loop iteration
#   17 and then bad luck from Italy for the 17th loop iteration
i=1
while [ $i -lt 21 ]
do
case $i in
4 )
printf "4\nbad luck from China\n";;
9 )
printf "9\nbad luck from Japan\n";;
17 )
printf "17\nbad luck from Italy\n";;
* )
echo $i;;
esac
i=$(( i+1 ))
done
