#!/usr/bin/env bash
#gives you information about the school file.

schoolFile="school"
if [ -e "$schoolFile" ]
then
    echo "school file exists"
    if [ ! -s "$schoolFile" ]
    then
        echo "school file is empty"
    else
        echo "school file is not empty"
    fi

    if [ -f "$schoolFile" ]
    then
        echo "school is a regular file"
    fi
    
elif [ ! -e "$schoolFile" ]
then
echo "school file does not exist"
fi
