#!/usr/bin/env bash
#displays all active IPv4 IPs on the machine it’s executed on.
ipv4_addresses=$(ipconfig | grep -Eo "IPv4 Address[^:]+: ([0-9]+\.){3}[0-9]+" | cut -d' ' -f 3)
for ipv4_address in $ipv4_addresses; do
  echo "$ipv4_address"
done
